### PR TITLE
REV-39: tweaks to "sign in" and "sign up"

### PR DESCRIPTION
**Pull request by nmashton**
Various changes to the sign in / sign up forms:
- Fixing capitalization in `forms.py` line 16
- Removing unwanted "address" field (on back-end and front-end alike)
- Changing the `login_redirect_url` value to be the lookup of `dashboard` instead of `home`

### CODE REVIEW

**Comment by kmtracey** [comment]
Ticket says after "sign up" the user should get redirected to dashboard, yet the change here is only after "sign in"...sign up redirect still goes to Home page. Requirements clarification may be needed here, I do think sign-in redirect should be to dashboard but I think sign-UP redirect is also wanted to be to dahsboard?

An odd side-effect of redirect to dashboard is a couple of now-briefly-visible messages towards the bottom of the page. These show and and then fade away. I suspect that is not what they are supposed to do...or that they are not supposed to be there at all. This is similar to what I was seeing with a form error on project creation (specifically the error I was hitting had to do with it not liking the address for organization I had filled in) not being visible to the user but rather appearing at the bottom of the page and then fading away. Whatever is going on here needs to be figured and fixed: if these messages are supposed to be visible to the user (in the case of the form error they certainly should be) then they need to be made visible. In the case of these login messages potentially they are not needed (certainly 2 of them are not needed) and should simply be removed?
screenshot from 2016-02-09 09 37 14

**Comment by nmashton** [comment]
Redirects should be good now, and the Toastr PR (#21) should fix the messages.

**Comment by kmtracey** [comment]
:+1:

**Comment by kmtracey** [comment]
There are duplicate messages but that can be addressed later as I expect it really has nothing to do with this change.

**Pull request merged**
